export enum TestValidationErrorKeys {
  NO_COMPLETE_TEST = 'NO_COMPLETE_TEST',
  NO_NAME_QUESTION = 'NO_NAME_QUESTION',
  NO_NAME_ANSWER = 'NO_NAME_ANSWER',
  NO_RIGHTS_ANSWER = 'NO_RIGHTS_ANSWER',
  NO_ANSWERS = 'NO_ANSWERS',
}
