export enum ExaminationValidationErrorKeys {
  NO_COMPLETE_EXAMINATION = 'NO_COMPLETE_EXAMINATION',
  NO_NAME_QUESTION = 'NO_NAME_QUESTION',
  NO_NAME_ANSWER = 'NO_NAME_ANSWER',
  NO_RIGHTS_ANSWER = 'NO_RIGHTS_ANSWER',
  NO_ANSWERS = 'NO_ANSWERS',
}
